services:

  ur-driver:
    image: husarion/ur:noetic
    container_name: ur-drive
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    volumes:
      - ./ur_calibration:/ur_calibration
    command: >
      roslaunch ur_bringup ur5e_rg2_bringup.launch 
        robot_ip:=10.15.20.4
        kinematics_config:=/ur_calibration/ur_calibration.yaml

  rg2-driver:
    image: husarion/ur-onrobot-rg2:noetic
    container_name: rg2-onrobot-driver
    restart: on-failure
    network_mode: host
    ipc: host
    tty: true
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: >
      roslaunch onrobot_rg2_driver bringup.launch

  rviz:
    image: husarion/ur:noetic
    container_name: rviz-gpu
    restart: on-failure
    network_mode: host
    ipc: host
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: rosrun rviz rviz -d /ros_ws/src/ur_bringup/config/rviz_config.rviz

  remote-desktop:
    image: donowak/remote-desktop:lan
    container_name: vnc-remote-desktop
    restart: on-failure
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ipc: host
    ports:
      - 8080:8080
    environment:
      - VNC_PASSWORD=husarion
      - DISPLAY