x-common-config:
  &common-config
  environment:
      - DISPLAY

x-nvidia-config:
  &nvidia-config
  runtime: nvidia
  environment:
    - DISPLAY
    - LIBGL_ALWAYS_SOFTWARE=1
    - QT_X11_NO_MITSHM=1 
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display

services:

  ur5e-rg2-gazebo:
    image: husarion/ur:noetic
    container_name: ur5e-rg2-gazebo
    restart: on-failure
    tty: true
    #<<: *nvidia-config
    <<: *common-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      roslaunch ur_bringup ur5e_rg2_gazebo.launch
        use_rviz:=true
