services:

  ur-driver:
    image: husarion/ur:noetic
    container_name: ur-drive
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    volumes:
      - ./ur_calibration:/ur_calibration
    command: >
      roslaunch ur_bringup ur5e_bringup.launch 
        robot_ip:=10.15.20.4
        kinematics_config:=/ur_calibration/ur_calibration.yaml

  velodyne:
    image: husarion/velodyne:noetic
    container_name: velodyne
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: >
      roslaunch velodyne_pointcloud VLP16_points.launch
        device_ip:=10.15.20.10
        frame_id:=velodyne
        port:=2368

  rviz:
    image: husarion/ur:noetic
    container_name: rviz
    restart: on-failure
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: rosrun rviz rviz -d /ros_ws/src/ur_bringup/config/rviz_config.rviz

  remote-desktop:
    image: donowak/remote-desktop:lan
    container_name: vnc-remote-desktop
    restart: on-failure
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ipc: host
    ports:
      - 8080:8080
    environment:
      - VNC_PASSWORD=husarion
      - DISPLAY