services:

  ur-driver:
    # image: husarion/ur5e:melodic
    build: ./../
    container_name: ur-drive
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    volumes:
      - ./../ur5e_moveit_config:/ros_ws/src/ur5e_moveit_config
      - ./../ur_bringup:/ros_ws/src/ur_bringup
      - ./../ur5e_onrobot_rg2_moveit_config:/ros_ws/src/ur5e_onrobot_rg2_moveit_config
    command: >
      roslaunch ur_bringup ur5e_rg2_bringup.launch 
        robot_ip:=10.15.20.4
        kinematics_config:=/ros_ws/src/ur_bringup/config/ur5e_calibration.yaml
        use_tool_communication:=false
        headless_mode:=false