services:

  ur-moveit-menager:
    image: husarion/ur:noetic
    container_name: ur-moveit-menager
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  
      # - ./<<dir/to/your/pkg>>:/ros_ws/src/ur5e_moveit_config
    command: roslaunch moveit_setup_assistant setup_assistant.launch