services:

  ur-calibration:
    image: husarion/ur:noetic
    container_name: ur-calibration
    restart: on-failure
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - ./ur_calibration:/ur_calibration
    command: >
      roslaunch ur_calibration calibration_correction.launch
        robot_ip:=10.15.20.4
        target_filename:="/ur_calibration/ur_calibration.yaml"