services:

  ur-calibration:
    image: husarion/ur:noetic
    container_name: ur-calibration
    restart: on-failure
    network_mode: host
    volumes:
      - ./ur_calibration:/ur_calibration
    command: >
      roslaunch ur_calibration calibration_correction.launch
        robot_ip:=10.15.20.4
        target_filename:="/ur_calibration/ur_calibration.yaml"